/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHome: typeof import('./src/components/AppHome.vue')['default']
    ReloadPWA: typeof import('./src/components/ReloadPWA.vue')['default']
  }
}
